#!/bin/bash

while [ $PWD != "/" ]; do
	if [ -e "topdir.inc" ]; then
		TOPDIR=`cat topdir.inc`
		for i in `find $TOPDIR -follow -name component.info`; do
			unset NAME
			. $i
			if [ $NAME == $1 ]; then
				echo $i
			fi
		done
		exit 0
	fi
	cd ..
done


