#!/bin/bash

while [ $PWD != "/" ]; do
	if [ -e "topdir.inc" ]; then
		TOPDIR=`cat topdir.inc`
		printf "%s%s %s%s " '-Wl,-rpath,' $TOPDIR/lib '-L' $TOPDIR/lib

		. component.info
		if [ "$REQUIRE" != "" ]; then
			for name in $REQUIRE; do
				unset FLAGS
				infofile=`dsvt-get-info-by-name $name`
				if [ "$infofile" == "" ]; then
					continue
				fi
				. $infofile

				if [ "$FLAGS" == "so" ]; then
					printf "%s%s " '-l' any$name
				fi
			done
		fi
		
		exit 0
	fi
	cd ..
done

